### ISSUE TITLE
Inconsistency of CMSIS-NN Quantization Method(Q-format) with ARM Documentation

### ISSUE THREAD

**Issue by Sudo42b** [ARM-software/CMSIS-NN#115]
Hello.

I am currently in the process of developing using the Q-Format (Qm.n) for quantization. However, upon reviewing the revision history, I noticed that starting from version 4.1.0, the q-format approach is no longer being followed. My current approach aligns with the methods outlined in the following ARM documentation links:
- [Compute the layer shifts](https://developer.arm.com/documentation/102591/2208/Compute-the-layer-shifts)
- [Choose a quantization scheme](https://developer.arm.com/documentation/102591/2208/Choose-a-quantization-scheme)

While TensorFlow Lite for Microcontrollers employs Zero Point and Scale Factor for quantization, which necessitates additional memory and floating-point operations, it appears that Q-format based quantization would be more suitable for Cortex-M processors due to these constraints.

Could you kindly provide a clear explanation for the necessity of this change? The absence of discussion regarding its impact on speed and accuracy has left me somewhat perplexed. Any insight into the rationale behind this decision would be greatly appreciated, as it would aid in understanding the best practices for quantization within the context of TensorFlow Lite for Microcontrollers and CMSIS-NN.

Thank you for your time and consideration.

**Comment by mansnils** [comment]
Thanks for the link! Why can't NNOM use the new/existing CMSIS-NN API?
Please note it also use shift operations. The scales are converted to integer multipliers and shifts before inference, and this is done before calling CMSIS-NN (before inference). And also performance should be better than the legacy API since development stopped long time ago.
