### ISSUE TITLE
The CMSIS-NN 5 pack is missing a file"arm_transpose_conv_get_buffer_sizes_s8", but it is present in the source code

### ISSUE THREAD

**Issue by theicett** [ARM-software/CMSIS-NN#140]
All files download from https://github.com/ARM-software/CMSIS-NN/releases/tag/v5.0.0

Install this pack on windows 10, open Keil MDK 5, and check CMSIS-NN 5.0.0 in runtime management

![image](https://github.com/ARM-software/CMSIS-NN/assets/31242576/59a3ebbb-778b-4211-a538-a3ae2abb3732)

The compilation fails due to the missing arm_transpose_conv_get_buffer_sizes_s8() function (the red one), "`Error: L6218E: Undefined symbol arm_transpose_conv_s8_get_buffer_size (referred from arm_transpose_conv_s8.o).`", Other functions (like the blue one) are fine

![9M{YOO0T7S%XS G04$7HIMB](https://github.com/ARM-software/CMSIS-NN/assets/31242576/6ddbc91a-97a3-45f7-8499-bc7efbcf6d27)

However, the source in the folder didn't miss the file, and the error went away after I added this file to my project.

Thank you for your time, if it's caused by my mistake, please help me point it out
@mansnils

**Comment by mansnils** [comment]
Hi @theicett 
I think that is a bug unfortunately. It's good that you could resolve and get around it. It should be fixed in https://github.com/ARM-software/CMSIS-NN/releases/tag/v6.0.0, which is the latest release and I recommend to use that if possible.
