### ISSUE TITLE
How to build on host

### ISSUE THREAD

**Issue by a1lu** [ARM-software/CMSIS-NN#27]
Hi,
I tried to build `CMSIS-NN` for a x86-64 host cpu and had some trouble to compile it using gcc 9.4.

Finally I ended with:
```
cmake  -D CMSIS_PATH="../../CMSIS_5" -DCMAKE_C_FLAGS:STRING="-D__GNUC_PYTHON__ -D__RESTRICT=__restrict" ..
```
Is this the recommended way to do it?
I had to specify `__RESTRICT`, otherwise I run into

```
/../cmsis/CMSIS-NN/Include/arm_nnsupportfunctions.h:967:62: error: expected ‘;’, ‘,’ or ‘)’ before ‘dst’
  967 | __STATIC_FORCEINLINE void arm_memcpy_q15(int16_t *__RESTRICT dst, const int16_t *__RESTRICT src, uint32_t block_size)

```

Best regards.

**Comment by felix-johnny** [comment]
@a1lu thanks for the question. This is related to https://github.com/ARM-software/CMSIS-NN/issues/26 

 CMSIS-NN does not provide an option for a host CPU build. Could you maybe elaborate on why it is built on a host? The suggestion provided in the linked ticket holds here too.

**Comment by a1lu** [comment]
Hi @felix-johnny
thanks for the fast response.
IIUC there is no support and we should define things like __RESTRICT by ourselves.

I want to test a model without using the provided python wrapper to avoid the python datatypes and things. So hopefully the pure C implementation is portable to the ARM core 1:1 at the end.
