### ISSUE TITLE
How to implement a neural network by using CMSIS-NN？

### ISSUE THREAD

**Issue by Raise-me-up** [ARM-software/CMSIS-NN#47]
Is there any tutorial?  I am confused about the cmsis-nn transform of nn.lstm, nn.layernorm, nn.prelu etc。

**Comment by felix-johnny** [comment]
@Raise-me-up thanks for the question. CMSIS-NN is an optimization library that provides optimization for some of the ML operators in TensorFlow Lite for Microcontrollers framework. 

https://github.com/ARM-software/CMSIS-NN/tree/main/Examples has some examples to see how one can get started on it.

**Comment by Raise-me-up** [comment]
@felix-johnny Thanks for your reply! I have read your example. However, it is based on Tensorflow lite micro library, and I just want to implement a neural network by using cmsis-nn purely, not the third party library. Are there any other examples?

**Comment by Raise-me-up** [comment]
@felix-johnny OK! Thanks for your detailed reply!
