### ISSUE TITLE
How to use arm_lstm_unidirectional_s16_s8? Are there any tutorials？

### ISSUE THREAD

**Issue by Raise-me-up** [ARM-software/CMSIS-NN#62]
Besides TFLM, are there any tutorials, especially the example codes,  for us to learn how to use the arm_lstm_unidirectional_s16_s8 function? It is so complicated.

**Comment by mansnils** [comment]
I think TFLM is a good starting point with a lot of supportive scripts. Other than that it might be a good idea so ask in the SIG Micro forum and/or join the monthly meetings: https://github.com/tensorflow/tflite-micro#getting-help

**Comment by Raise-me-up** [comment]
@mansnils OK, thanks!
